services:
  app:
    build: ./config/.
    container_name: smalltalk
    tty: true
    command: /bin/bash
    volumes: 
      - ./app:/root/app
    networks: 
      - smalltalk
    
  db:
    image: mysql
    container_name: mysql
    hostname: 'mysql-host'
    restart: always
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --innodb_use_native_aio=0
    environment:
      MYSQL_DATABASE: 'account'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql
    networks:
      - smalltalk

volumes:
  db:
    driver: local

networks:
  smalltalk:
    driver: bridge
